# Generated by Django 3.2.13 on 2022-05-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_blood'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('noday', models.CharField(max_length=100)),
            ],
        ),
    ]
