# Generated by Django 3.2.13 on 2022-05-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('btype', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('bankname', models.CharField(max_length=100)),
                ('nounit', models.CharField(max_length=100)),
                ('price', models.TextField(max_length=500)),
            ],
        ),
    ]
