# Generated by Django 3.2.6 on 2022-06-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_bloodrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='image',
            field=models.ImageField(default=1, upload_to='pics/'),
            preserve_default=False,
        ),
    ]
